### ISSUE TITLE
Move the server code to Node.js

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#17]
Hello! An issue so that we keep this in mind: As we discussed previously, I'd really prefer to run/maintain a nodejs+express server. The python server is ment to be a temporary solution for quickly designing/testing the API.

**Comment by jbpoline** [comment]
One advantage of the python server is that if we want to play with more stat-ish package  it would really help, most people can easily do python - for instance all the machine learning stuff from sk-learn or topic model stuff

**Comment by r03ert0** [comment]
It's still possible to call python code from the javascript code

**Comment by jbpoline** [comment]
I need to learn javascript right now :)

**Comment by r03ert0** [comment]
a free book : )
https://www.sitepoint.com/premium/books/javascript-novice-to-ninja

**Comment by jbpoline** [comment]
how about this ? 
https://www.destroyallsoftware.com/talks/wat

**Comment by r03ert0** [comment]
http://pypyjs.org/
:p

**Comment by jbpoline** [comment]
hum: seems to be missing some basics so far :)  I wonder if this is because numpy links to c or fortran libs

>>> import numpy as np
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named numpy
>>>

**Comment by jbpoline** [comment]
As discussed in Vancouver, we keep the server side as it at the moment - Anisha and Roberto to work on the front end. Neel is working on making the server very easy to restart and redeploy as soon as CI is ok with the tests
