### ISSUE TITLE
seach not yielding any results and hanging

### ISSUE THREAD

**Issue by jbpoline** [OpenNeuroLab/brainspell-neo#19]
search with "vision schizophrenia" seems to be hanging :
https://brainspell.herokuapp.com/search?q=vision+schizophrenia&req=t
Is this replicable on your machines ?

**Comment by Sharabesh** [comment]
Yes, I am seeing this as well. This appears to be a new issue. I'll look into it.

**Comment by neelsomani** [comment]
Search fails on anything with more than one word (or a space). One fix is to replace spaces in queries with the SQL wildcard character (%). I think we had that before, but it must have been taken out at some point.

**Comment by Sharabesh** [comment]
Fixed!

**Comment by r03ert0** [comment]
I get the following error when clicking on JB's link:

```
[.Offscreen-For-WebGL-0x7ff55c0cb200]RENDER WARNING: Render count or primcount is 0.
search?q=vision+schizophrenia&req=t:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by neelsomani** [comment]
Fixed with the latest commit. (Search widgets are no longer rendered if there are no coordinates received.)
