### ISSUE TITLE
Table editing functionalities

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#20]
The following table editing functionalities still need to be translated from brainspell.org:

- [x] * Delete row: Sometimes neurosynth tables include incorrect rows  
- [x] * Paste table from text file: Useful for manual addition of tables (used for example by the NIDM tests)
- [x] * Split a table: Sometimes neurosynth tables include data from many experiments
- [x] * Login-dependent UI: Editing functionalities should be only visible to loged-in users
- [x] * Flag table as correct/incorrect
- [x] * Edition of table titles and captions: this provides a correspondance between the tables in brainspell and the tables in the source article
- [x] * Add discussion: To allow users to discuss ambiguous choices
- [x] * Ontology tagging: The main utility of brainspell is the manual annotation of the experiments: 

- [x] (1) annotation with multiple ontologies, 
- [x] (2) display of ontology terms,
- [x]  (3) filtering, 
- [x] (4) display term definitions, 
- [ ] 

- [x] (5) voting [agree, disagree, retract].
- [x] * The displayed information is different for three different roles: (1) not loged user [only basic/consensual information displayed], (2) loged user but not author of annotations in the current article [user is given the possibility to add its own annotations], (3) loged user author of annotations in the current article [the user is shown her own annotations and is given the possibility to change them]

**Comment by jbpoline** [comment]
Are there things that you feel should be prioritized ? (so that Sharabesh and Neel don't get despondant :)

**Comment by r03ert0** [comment]
All the UI could be left for later :)
The priority should really be the handling of these functionalities through the API (modification of coordinates, tagging, voting, role-base filtering of the json data returned by the server, etc.)

what do you think?

**Comment by jbpoline** [comment]
Sounds reasonable to me  @Sharabesh  @neelsomani what do you think ?

**Comment by Sharabesh** [comment]
Could you clarify what you meant by this comment: 
* Edition of table titles and captions: this provides a correspondance between the tables in brainspell and the tables in the source article

Is this just specifying the table identifier in the article itself?

**Comment by r03ert0** [comment]
Yes:

In an article pdf (or html) each table is labelled with a Table number, it has a title and a caption. In brainspell-neo the tables are labelled using an arbitraty experiment number (for example, 
`Experiment 3977`). For the moment, the only way a user can establish the correspondance between a table in an article and an experiment in brainspell-neo is by comparing the list of coordinates (by the way, is the order of the coordinates conserved?)

In brainspell(-arche) the title and caption of each table is displayed, if available. These data is not always correctly parsed, and sometimes have inacuracies. The fields are then editable in brainspell-arche, so that users can correct them.

Another important point is that sometimes papers combine in a single big table the results of many individual experiments. The tools for splitting tables were ment to help with this issue. Aman Badhwar had suggested a way of naming the titles resulting from a split of an original table, so that they associated back. Maybe the history of splits and merges of a table could be stored?
