### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#21]
This article doesn't load:

https://brainspell.herokuapp.com/view-article?id=24996404

this is the error in the web console:

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (view-article:212)
    at j (jquery.js:2)
    at Object.fireWith (jquery.js:2)
    at x (jquery.js:4)
    at XMLHttpRequest.b (jquery.js:4)
```

**Comment by Sharabesh** [comment]
Fixed. There were some edge cases associated with this article (having no mesh descriptors to display).

**Comment by r03ert0** [comment]
thank you!

**Comment by r03ert0** [comment]
sorry... now I get the infamous:
`Mixed Content: The page at 'https://brainspell.herokuapp.com/view-article?id=24996404' was loaded over HTTPS, but requested an insecure script 'http://spin.js.org/spin.min.js'. This request has been blocked; the content must be served over HTTPS`

**Comment by Sharabesh** [comment]
Yes I see this now. It must be a result of how we are handling Github user accounts for collections. If you allow your browser to load unsafe scripts, the page will load, but I'll get a better solution pushed.

**Comment by Sharabesh** [comment]
Ok fixed this as well.

**Comment by r03ert0** [comment]
it's working, thanks!
