### ISSUE TITLE
Possibility to retract a vote to a tag (agree/disagree)

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#28]
It should be possible to retract a vote to a tag. In brainspell-neo it's like this:

<img width="597" alt="screen shot 2017-04-22 at 10 29 21" src="https://cloud.githubusercontent.com/assets/2310732/25302784/a7edbbf8-2746-11e7-86bb-73b38a8b87c2.png">

It used to be the case that brainspell-arche had a 'retract' button, but now I just checked and it's not there anymore... I may have reverted it inadvertedly

**Comment by r03ert0** [comment]
(the priority should be to add the possibility of a vote retraction to the API)

**Comment by neelsomani** [comment]
The API endpoint I just created allows users to toggle their vote by sending the same API request. (If a user is logged in and they click "Agree" twice, the first click will add a vote to "Agree", and the second click will retract it.)

**Comment by r03ert0** [comment]
When a user lands in a tag where they have voted, they should see something like `Agree (5, including you) Disagree (2)`; so that they know what their vote was.

**Comment by neelsomani** [comment]
Added in latest commit:

<img width="609" alt="screen shot 2017-04-22 at 11 00 57" src="https://cloud.githubusercontent.com/assets/7029855/25307413/45a8046c-2755-11e7-9ef4-be2675bebeb1.png">

**Comment by neelsomani** [comment]
Added in latest commit:

<img width="628" alt="screen shot 2017-04-22 at 12 14 28" src="https://cloud.githubusercontent.com/assets/7029855/25307415/4ef73a06-2755-11e7-9c1a-fc43de0ce9f7.png">

**Comment by r03ert0** [comment]
you rule!! : D
