### ISSUE TITLE
Visual feedback on tag votes

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#29]
It would be nice to provide visual feedback on the votes cumulated by a tag: more agree, more disagree, as many agrees than disagrees, no vote. Here's how this is displayed in brainspell-arche:

<img width="832" alt="screen shot 2017-04-22 at 10 33 02" src="https://cloud.githubusercontent.com/assets/2310732/25302823/6802fd22-2747-11e7-944e-a05bbac84b3d.png">

green: more agre
red: more disagree
orange: same
none: no votes

**Comment by neelsomani** [comment]
Added with latest commit:

<img width="609" alt="screen shot 2017-04-22 at 11 00 57" src="https://cloud.githubusercontent.com/assets/7029855/25306850/10d60c34-274b-11e7-9fc5-3dd7b6d6f14e.png">
