### ISSUE TITLE
Creating an API Endpoint to edit tags, coordinates, and authors for an article

### ISSUE THREAD

**Issue by Sharabesh** [OpenNeuroLab/brainspell-neo#3]
Finalize the API Endpoint to allow users to contribute additional MeSH descriptor tags for a given article, table coordinates for a given experiment, and authors for any given article (optional).

**Comment by neelsomani** [comment]
Still need to create JSON endpoint to add/delete descriptors. (Descriptors should be for experiments, rather than for the whole article.)

**Comment by r03ert0** [comment]
It would be important to keep track of the original MeSH descriptors (those created by the NCBI and available through pubmed), and maybe distinguish them from the user-contributed ones.

In each article there are these two levels: the article level and the experiment level. MeSH descriptors are for the moment article-level only, and Cognitive atlas tasks, Cognitive atlas domains and Brainmap domains are experiment-level only. Ideally, the API should be able to handle both levels, and arbitrary ontologies. As a simplification, in brainspell-arche, the article-level is "experiment 0" and the experiment-level have numbers >0.
