### ISSUE TITLE
Add to Collection Functionality on the Search Page Erroring

### ISSUE THREAD

**Issue by Sharabesh** [OpenNeuroLab/brainspell-neo#39]
function SaveCollection yielding error message: 

`tornado.auth.AuthError: Error response HTTP 422: Unprocessable Entity fetching <Repo URL>
`

**Comment by Sharabesh** [comment]
I think this one is still having some bugs: 

```
simplejson.scanner.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
ERROR:tornado.access:500 POST /add-to-collection?pmid=18372290&collection=brainspell-collection-Trial4 (::1) 202.39ms
```

Might be worth keeping it open for the time being.

**Comment by neelsomani** [comment]
It's because the PostgreSQL table itself is corrupted, but there's nothing wrong with the code itself anymore. (I fixed it last night.) Go ahead and try deleting your collections from the collections column of Users, and deleting your GitHub repos.
