### ISSUE TITLE
Add API Keys 

### ISSUE THREAD

**Issue by Sharabesh** [OpenNeuroLab/brainspell-neo#4]
Provide each user with an API key (potentially a password hash) that can be verified before a database operation.

**Comment by neelsomani** [comment]
Show a user’s own information (ratings, e.g.) if they’re logged in. (Detect with API key.)

**Comment by neelsomani** [comment]
Compute JSON diff and store with user metadata when a database operation is done.

**Comment by neelsomani** [comment]
Added API keys with latest commit
