### ISSUE TITLE
Create popup when creating a collection to ask for permissions

### ISSUE THREAD

**Issue by Sharabesh** [OpenNeuroLab/brainspell-neo#61]
Explain that we will not be accessing non-Brainspell repositories prior to asking for permissions.

**Comment by akeshavan** [comment]
Done!

<img width="1044" alt="screenshot 2018-04-18 16 12 39" src="https://user-images.githubusercontent.com/972008/38962753-95d8f85c-4323-11e8-801c-c74d96a2cc75.png">
