### ISSUE TITLE
Add features for users to save articles, collections, etc. (add a user-metadata table)

### ISSUE THREAD

**Issue by neelsomani** [OpenNeuroLab/brainspell-neo#9]

**Comment by Sharabesh** [comment]
Collections: 
- Add, Remove articles  
- Shared between users (eventually?) 
- Versions of a collection (Revert to a previous version) (JSON DIFF?)
- Previous versions of the annotations?

**Comment by Sharabesh** [comment]
Allow users to comment and add indepdent tags to an article.

**Comment by Sharabesh** [comment]
Version control of the collections, Connect to Github (have the collection as a repository --> A collection can be shared on github and be forked to share changes.

**Comment by neelsomani** [comment]
What's left to finish up for this issue?

**Comment by Sharabesh** [comment]
In my opinion, nothing. Github takes care of most of these features.
